trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

pool: 
  vmImage: 'ubuntu-20.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'codescan.abb.com'
    scannerMode: 'CLI'
    configMode: 'file'
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)'
- task: Npm@1
  displayName: 'npm run validate'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'run validate'    
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)'
    customCommand: 'run buildProd'
- task: SonarQubeAnalyze@5
  condition: succeededOrFailed()
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
